// Íconos genéricos del juego base (vanilla). Se pueden usar sin crear gráficos propios.

export const DEFAULT_ICON = 'GFX_goal_generic_production'

export const GENERIC_ICONS: { value: string; label: string }[] = [
  { value: 'GFX_goal_generic_production', label: 'Producción' },
  { value: 'GFX_goal_generic_production2', label: 'Producción 2' },
  { value: 'GFX_goal_generic_construct_civ_factory', label: 'Fábrica civil' },
  { value: 'GFX_goal_generic_construct_mil_factory', label: 'Fábrica militar' },
  { value: 'GFX_goal_generic_construct_naval_dockyard', label: 'Astillero' },
  { value: 'GFX_goal_generic_construct_infrastructure', label: 'Infraestructura' },
  { value: 'GFX_goal_generic_construction', label: 'Construcción' },
  { value: 'GFX_goal_generic_consumer_goods', label: 'Bienes de consumo' },
  { value: 'GFX_goal_generic_oil_refinery', label: 'Refinería' },
  { value: 'GFX_goal_generic_small_arms', label: 'Armas ligeras' },
  { value: 'GFX_goal_generic_allies_build_infantry', label: 'Infantería' },
  { value: 'GFX_goal_generic_army_doctrines', label: 'Doctrinas de ejército' },
  { value: 'GFX_goal_generic_army_motorized', label: 'Motorizados' },
  { value: 'GFX_goal_generic_army_tanks', label: 'Tanques' },
  { value: 'GFX_goal_generic_army_artillery', label: 'Artillería' },
  { value: 'GFX_goal_generic_army_artillery2', label: 'Artillería 2' },
  { value: 'GFX_goal_generic_cavalry', label: 'Caballería' },
  { value: 'GFX_goal_generic_special_forces', label: 'Fuerzas especiales' },
  { value: 'GFX_goal_generic_fortify_city', label: 'Fortificar ciudad' },
  { value: 'GFX_goal_generic_defence', label: 'Defensa' },
  { value: 'GFX_goal_generic_build_airforce', label: 'Fuerza aérea' },
  { value: 'GFX_goal_generic_air_fighter', label: 'Cazas' },
  { value: 'GFX_goal_generic_air_bomber', label: 'Bombarderos' },
  { value: 'GFX_goal_generic_air_doctrine', label: 'Doctrina aérea' },
  { value: 'GFX_goal_generic_air_production', label: 'Producción aérea' },
  { value: 'GFX_goal_generic_air_naval_bomber', label: 'Bombardero naval' },
  { value: 'GFX_goal_generic_build_navy', label: 'Armada' },
  { value: 'GFX_goal_generic_navy_doctrines_tactics', label: 'Doctrina naval' },
  { value: 'GFX_goal_generic_navy_submarine', label: 'Submarinos' },
  { value: 'GFX_goal_generic_navy_carrier', label: 'Portaaviones' },
  { value: 'GFX_goal_generic_navy_battleship', label: 'Acorazados' },
  { value: 'GFX_goal_generic_wolf_pack', label: 'Manada de lobos' },
  { value: 'GFX_goal_generic_national_unity', label: 'Unidad nacional' },
  { value: 'GFX_goal_generic_political_pressure', label: 'Presión política' },
  { value: 'GFX_goal_generic_propaganda', label: 'Propaganda' },
  { value: 'GFX_goal_generic_neutrality_focus', label: 'Neutralidad' },
  { value: 'GFX_goal_generic_alliance', label: 'Alianza' },
  { value: 'GFX_goal_generic_improve_relations', label: 'Mejorar relaciones' },
  { value: 'GFX_goal_generic_positive_trade_relations', label: 'Relaciones comerciales' },
  { value: 'GFX_goal_generic_trade', label: 'Comercio' },
  { value: 'GFX_goal_generic_dangerous_deal', label: 'Trato peligroso' },
  { value: 'GFX_goal_generic_forceful_treaty', label: 'Tratado forzoso' },
  { value: 'GFX_goal_generic_intelligence_exchange', label: 'Intercambio de inteligencia' },
  { value: 'GFX_goal_generic_scientific_exchange', label: 'Intercambio científico' },
  { value: 'GFX_goal_generic_secret_weapon', label: 'Arma secreta' },
  { value: 'GFX_goal_generic_radar', label: 'Radar' },
  { value: 'GFX_goal_generic_demand_territory', label: 'Exigir territorio' },
  { value: 'GFX_goal_generic_more_territorial_claims', label: 'Más reclamaciones' },
  { value: 'GFX_goal_generic_territory_or_war', label: 'Territorio o guerra' },
  { value: 'GFX_goal_generic_major_war', label: 'Gran guerra' },
  { value: 'GFX_goal_generic_occupy_start_war', label: 'Iniciar guerra' },
  { value: 'GFX_goal_generic_occupy_states_ongoing_war', label: 'Ocupar estados' }
]
