// Íconos genéricos del juego (ya existen en HOI4, no hace falta añadir imágenes).
// [nombre GFX, descripción en español, emoji para la vista previa en la app]
export const FOCUS_ICONS: [string, string, string][] = [
  ['GFX_goal_unknown', 'Desconocido', '❓'],
  ['GFX_goal_generic_production', 'Producción', '🏭'],
  ['GFX_goal_generic_production2', 'Producción 2', '⚙️'],
  ['GFX_goal_generic_construct_civ_factory', 'Fábrica civil', '🏗️'],
  ['GFX_goal_generic_construct_mil_factory', 'Fábrica militar', '🔧'],
  ['GFX_goal_generic_construct_infrastructure', 'Infraestructura', '🛤️'],
  ['GFX_goal_generic_construct_naval_dockyard', 'Astillero', '⚓'],
  ['GFX_goal_generic_consumer_goods', 'Bienes de consumo', '🛒'],
  ['GFX_goal_generic_research', 'Investigación', '🔬'],
  ['GFX_goal_generic_scientific_exchange', 'Intercambio científico', '🧪'],
  ['GFX_goal_generic_secret_weapon', 'Arma secreta', '☢️'],
  ['GFX_goal_generic_radar', 'Radar', '📡'],
  ['GFX_goal_generic_army_doctrines', 'Doctrina terrestre', '📜'],
  ['GFX_goal_generic_allies_build_infantry', 'Infantería', '🪖'],
  ['GFX_goal_generic_small_arms', 'Armas ligeras', '🔫'],
  ['GFX_goal_generic_army_artillery', 'Artillería', '💥'],
  ['GFX_goal_generic_army_motorized', 'Motorizados', '🚚'],
  ['GFX_goal_generic_army_tanks', 'Tanques', '🛡️'],
  ['GFX_goal_generic_special_forces', 'Fuerzas especiales', '🎯'],
  ['GFX_goal_generic_air_doctrine', 'Doctrina aérea', '✈️'],
  ['GFX_goal_generic_air_production', 'Producción aérea', '🛩️'],
  ['GFX_goal_generic_air_fighter', 'Cazas', '🛫'],
  ['GFX_goal_generic_air_bomber', 'Bombarderos', '💣'],
  ['GFX_goal_generic_navy_doctrines_tactics', 'Doctrina naval', '🚢'],
  ['GFX_goal_generic_navy_submarine', 'Submarinos', '🐟'],
  ['GFX_goal_generic_defence', 'Defensa', '🧱'],
  ['GFX_goal_generic_fortify_city', 'Fortificar ciudad', '🏰'],
  ['GFX_goal_generic_major_war', 'Gran guerra', '⚔️'],
  ['GFX_goal_generic_occupy_states_ongoing_war', 'Ocupar estados', '🚩'],
  ['GFX_goal_generic_demand_territory', 'Exigir territorio', '🗺️'],
  ['GFX_goal_generic_territory_or_war', 'Territorio o guerra', '⚖️'],
  ['GFX_goal_generic_more_territorial_claims', 'Más reclamaciones', '📌'],
  ['GFX_goal_generic_alliance', 'Alianza', '🤝'],
  ['GFX_goal_generic_improve_relations', 'Mejorar relaciones', '💬'],
  ['GFX_goal_generic_positive_trade_relations', 'Comercio', '💰'],
  ['GFX_goal_generic_trade', 'Comercio 2', '📦'],
  ['GFX_goal_generic_dangerous_deal', 'Trato peligroso', '🐍'],
  ['GFX_goal_generic_political_pressure', 'Presión política', '🗳️'],
  ['GFX_goal_generic_propaganda', 'Propaganda', '📢'],
  ['GFX_goal_generic_national_unity', 'Unidad nacional', '🏛️'],
  ['GFX_goal_generic_neutrality_focus', 'Neutralidad', '🕊️']
]

export const iconEmoji = (gfx: string): string => FOCUS_ICONS.find((i) => i[0] === gfx)?.[2] ?? '❓'
